#! /usr/bin/env python

import rospy
from geometry_msgs.msg import Twist


class TurtleBot:

    def __init__(self):

        rospy.init_node('controller_reassemble_py_n')
        self.pub = rospy.Publisher('/cmd_vel', Twist, queue_size=1)
        self.rate = rospy.Rate(10)

    def move2goal(self):

        msg = Twist()

        msg.linear.x = 0.5

        while not rospy.is_shutdown():
            print('moving')
            self.pub.publish(msg)
            self.rate.sleep()


if __name__ == '__main__':
    try:
        tb = TurtleBot()
        tb.move2goal()
    except rospy.ROSInterruptException:
        pass

